# Outgoing Email Settings
# email:
#   smtp: 
#   port: 
#   source_email: 
#   target_email: 
#   subject: 
#   password_file: 

# PushBullet Settings
# pushbullet:
#   api_key:
#   tag:

vote_filter: 1
notify_min_rank: 8